language: node_js
node_js:
  - lts/*
before_script:
  - npm ci
script:
  - npm run coverage
after_script:
  - npm install codeclimate-test-reporter && cat coverage/lcov.info | codeclimate-test-reporter
